using Modus.Core.Events;
using Modus.Core.Messaging;
using Modus.Core.Plugins;
using Xunit;

namespace Modus.Core.Tests.Events;

public sealed class DomainEventGenericTests
{
    // ── DomainEvent<TPayload> ──────────────────────────────────────────────

    [Fact]
    public void Constructor_GivenNameAndTypedPayload_ExpectedBothPropertiesAccessible()
    {
        var ev = new DomainEvent<string>("OrderCreated", "payload-value");

        Assert.Equal("OrderCreated", ev.Name);
        Assert.Equal("payload-value", ev.Payload);
    }

    [Fact]
    public void Constructor_GivenNullReferenceTypePayload_ExpectedArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => new DomainEvent<string>("OrderCreated", null!));
    }

    [Fact]
    public void Constructor_GivenValueTypePayload_ExpectedDefaultValueAccepted()
    {
        var ev = new DomainEvent<int>("CounterReset", 0);

        Assert.Equal("CounterReset", ev.Name);
        Assert.Equal(0, ev.Payload);
    }

    // ── DomainEventEnvelope<TPayload> ─────────────────────────────────────

    [Fact]
    public void Constructor_GivenTypedEvent_ExpectedEventAndSourcePluginIdCaptured()
    {
        var ev = new DomainEvent<string>("OrderCreated", "data");
        var sourceId = new PluginId("Plugin.Orders");

        var envelope = new DomainEventEnvelope<string>(ev, sourceId);

        Assert.Equal(ev, envelope.Event);
        Assert.Equal(sourceId, envelope.SourcePluginId);
    }

    [Fact]
    public void Constructor_GivenNoEventId_ExpectedNonEmptyGuidAutoGenerated()
    {
        var ev = new DomainEvent<string>("OrderCreated", "data");
        var envelope = new DomainEventEnvelope<string>(ev, new PluginId("Plugin.Orders"));

        Assert.NotEqual(Guid.Empty, envelope.EventId);
    }

    [Fact]
    public void Constructor_GivenNoOccurredAt_ExpectedOccurredAtDefaultsToUtcNow()
    {
        var before = DateTimeOffset.UtcNow;
        var ev = new DomainEvent<string>("OrderCreated", "data");
        var envelope = new DomainEventEnvelope<string>(ev, new PluginId("Plugin.Orders"));
        var after = DateTimeOffset.UtcNow;

        Assert.InRange(envelope.OccurredAtUtc, before, after);
    }

    [Fact]
    public void Constructor_GivenHeaders_ExpectedHeadersCopiedWithOrdinalStringComparison()
    {
        var headers = new Dictionary<string, string> { ["tenant"] = "alpha" };
        var ev = new DomainEvent<string>("OrderCreated", "data");
        var envelope = new DomainEventEnvelope<string>(
            ev, new PluginId("Plugin.Orders"), Headers: headers);

        // Value accessible
        Assert.Equal("alpha", envelope.Headers["tenant"]);

        // Mutation of original does not affect the envelope's copy
        headers["tenant"] = "beta";
        Assert.Equal("alpha", envelope.Headers["tenant"]);

        // Ordinal comparison: keys differing only by case are distinct
        Assert.False(envelope.Headers.ContainsKey("TENANT"));
    }

    [Fact]
    public void Constructor_GivenNullHeaders_ExpectedEmptyDictionaryCreated()
    {
        var ev = new DomainEvent<string>("OrderCreated", "data");
        var envelope = new DomainEventEnvelope<string>(
            ev, new PluginId("Plugin.Orders"), Headers: null);

        Assert.Empty(envelope.Headers);
    }
}
